PaystackPaymentIntegration/Controllers/TransactionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PaystackPaymentIntegration.Models.DataModel;
using PaystackPaymentIntegration.Models.Entities;
using PaystackPaymentIntegration.Models.DTOs.Writable;
using PaystackPaymentIntegration.Models;

namespace PaystackPaymentIntegration.Controllers
{
    public class TransactionController : Controller
    {
        public async Task<ActionResult> Index()
        {
            using (var uow = new PaymentUOW())
            {
                var results = await uow.Transaction.GetAllTransactions();
                //ViewBag.Results = results;

                return View(results);
            } 
        }

        // New Payment View
        public ActionResult make_payment()
        {
            return View();
        }

        //Make New Payment
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> make_payment([Bind(Include = "email,amount")] TransactionDTOW model)
        {
            using (var uow = new PaymentUOW())
            {
                try
                {
                    if (ModelState.IsValid)
                    {
                        var errorMessage = string.Empty;

                        //Initialize Transaction
                        var initializeResponse = uow.Transaction.InitializeTransaction(model.email, model.amount);

                        if (initializeResponse.Status)
                        {
                            //save records to database
                            var newRecord = new transaction_record
                            {
                                email = model.email,
                                amount = model.amount,
                                reference = initializeResponse.Data.Reference,
                                created_date = DateTime.UtcNow
                            };

                            uow.Transaction.Add(newRecord);
                            await uow.CompleteAsync();

                            Response.Redirect(initializeResponse.Data.AuthorizationUrl);
                        }
                        else
                        {
                            errorMessage = initializeResponse.Message;
                        }

                        ViewBag.ErrorMessage = errorMessage;
                        return View("PaymentError");
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            return View(model);
        }

        //View Payment Details
        public ActionResult payment_details(string tranxRef)
        {
            if (tranxRef == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var result = new PaymentUOW().Transaction.VerifyTransaction(tranxRef);

            ViewBag.Details = result;

            return View(result);
        }

        //Calling With Ajax from UI
        public JsonResult InitializePayment(TransactionDTOW model)
        {
            using (var uow = new PaymentUOW())
            {
                var response = uow.Transaction.InitializeTransaction(model.email, model.amount);

                if (response.Status == true)
                {
                    return Json(new { error = false, result = response }, JsonRequestBehavior.AllowGet);
                }
                return Json(new { error = true, result = response }, JsonRequestBehavior.AllowGet);
            }
        }

        //Save to DB With Ajax from UI
        public JsonResult SavePayment(string email, int amount, string reference)
        {
            using (var uow = new PaymentUOW())
            {
                var newRecord = new transaction_record
                {
                    email = email,
                    amount = amount,
                    reference = reference,
                    created_date = DateTime.UtcNow
                };

                uow.Transaction.Add(newRecord);
                int response = uow.Complete();

                if (response > 0)
                {
                    return Json(new { error = false, result = "success" }, JsonRequestBehavior.AllowGet);
                }
                return Json(new { error = true, result = "error" }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

PaystackPaymentIntegration/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Transaction", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Transaction", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>